parser: '@typescript-eslint/parser'

env:
    browser: true
    node: true
    es6: true

settings:
    react:
        version: detect

parserOptions:
    project: tsconfig.json
    tsconfigRootDir: ./
    sourceType: module
    ecmaVersion: 2019
    noWatch: true
    ecmaFeatures:
        jsx: true

plugins:
    - '@typescript-eslint'
    - prettier
    - react

extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:prettier/recommended'
    - 'plugin:react/recommended'
    - 'prettier/@typescript-eslint'

rules:
    indent: 0
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    '@typescript-eslint/camelcase': 0
    '@typescript-eslint/no-var-requires': 0
    '@typescript-eslint/explicit-function-return-type': 0
