[build]
    publish = "public/"
    command = "gatsby build"

[[redirects]]
    from = "http://giladpeleg.com/*"
    to = "https://www.giladpeleg.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://giladpeleg.com/*"
    to = "https://www.giladpeleg.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://www.giladpeleg.com/*"
    to = "https://www.giladpeleg.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://elastic-hamilton-a5c549.netlify.com/*"
    to = "https://www.giladpeleg.com/:splat"
    status = 301
    force = true

[[headers]]
  for = "/*"

  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; object-src 'none'; connect-src 'self'; img-src 'self' data:; media-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; worker-src 'self'; report-uri https://giladpeleg.report-uri.com/r/d/csp/enforce"
    Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://giladpeleg.report-uri.com/a/d/g"}],"include_subdomains":true}'
    Feature-Policy = "fullscreen 'self'"
