[build]
    publish = "public/"
    command = "gatsby build"

[[redirects]]
    from = "http://giladpeleg.com/*"
    to = "https://www.giladpeleg.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://giladpeleg.com/*"
    to = "https://www.giladpeleg.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://www.giladpeleg.com/*"
    to = "https://www.giladpeleg.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://elastic-hamilton-a5c549.netlify.com/*"
    to = "https://www.giladpeleg.com/:splat"
    status = 301
    force = true

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "fullscreen 'self'"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = '''
        default-src 'self' www.google-analytics.com www.giladpeleg.com;
        font-src 'self' www.google-analytics.com www.giladpeleg.com data:;
        img-src 'self' www.google-analytics.com www.giladpeleg.com data:;
        media-src 'self' www.giladpeleg.com;
        object-src 'none';
        prefetch-src 'self' www.google-analytics.com www.giladpeleg.com;
        script-src 'self' 'unsafe-inline' www.google-analytics.com www.giladpeleg.com;
        style-src 'self' 'unsafe-inline' www.giladpeleg.com;
        worker-src 'self' www.giladpeleg.com;
        report-uri https://giladpeleg.report-uri.com/r/d/csp/enforce
        '''
    Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://giladpeleg.report-uri.com/a/d/g"}],"include_subdomains":true}'
