[build]
    publish = "public/"
    command = "gatsby build"

[[redirects]]
    from = "http://giladpeleg.com/*"
    to = "https://www.giladpeleg.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://giladpeleg.com/*"
    to = "https://www.giladpeleg.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://www.giladpeleg.com/*"
    to = "https://www.giladpeleg.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://elastic-hamilton-a5c549.netlify.com/*"
    to = "https://www.giladpeleg.com/:splat"
    status = 301
    force = true

[[headers]]
  for = "/*"

  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
