name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 14
              uses: actions/setup-node@v1
              with:
                  node-version: '14'
            - name: install deps
              run: npm ci
            - name: verify & build
              run: |
                  npm run develop 2>&1 &
                  sleep 30
                  npm run codegen
                  npm run verify
                  npm run build
