name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: '12'
            - name: install deps
              run: npm ci
            - name: verify
              run: npm run verify
            - name: build
              run: npm run build
